import { CompanyProfile, ProjectInput } from "./types";

export const MOCK_COMPANIES: CompanyProfile[] = [
  {
    id: "co-1",
    legalName: "Piedmont Electrical Group, LLC",
    dba: "Piedmont Electric",
    entityType: "llc",
    incorporatedStates: ["NC"],
    foreignQualifications: ["SC"],
    licenses: [
      { id: "l1", state: "NC", trade: "electrical", classification: "Unlimited", licenseNumber: "NC-34211-U", qualifier: "Maria Santos", issuedDate: "2021-07-12", expiryDate: "2027-06-30", status: "active" },
      { id: "l2", state: "SC", trade: "electrical", classification: "Group 4", licenseNumber: "SC-ME-11842", qualifier: "Maria Santos", issuedDate: "2022-03-01", expiryDate: "2026-10-31", status: "active" },
      { id: "l3", state: "VA", trade: "electrical", classification: "Class B", licenseNumber: "VA-2701-089123", qualifier: "James Park", issuedDate: "2023-01-15", expiryDate: "2026-12-31", status: "active" },
    ],
    qualifiers: [
      { name: "Maria Santos", trades: ["electrical"], states: ["NC", "SC"] },
      { name: "James Park", trades: ["electrical"], states: ["VA"] },
    ],
    insurance: { generalLiability: { amount: 2000000, expiry: "2027-03-01" }, workersComp: true },
    bonds: [{ state: "NC", amount: 10000 }],
    registrations: [{ jurisdiction: "Mecklenburg County, NC", type: "Business Registration", expiry: "2027-01-15" }],
    createdAt: "2024-01-10",
  },
  {
    id: "co-2",
    legalName: "Carolina Climate Systems Inc.",
    dba: "Carolina Climate",
    entityType: "corp",
    incorporatedStates: ["SC"],
    foreignQualifications: [],
    licenses: [
      { id: "l4", state: "SC", trade: "hvac", classification: "Group 5 - Unlimited", licenseNumber: "SC-HVAC-9021", qualifier: "David Kim", issuedDate: "2020-05-20", expiryDate: "2027-10-31", status: "active" },
      { id: "l5", state: "NC", trade: "hvac", classification: "H3 — Class I", licenseNumber: "NC-H-28411", qualifier: "David Kim", issuedDate: "2023-09-01", expiryDate: "2026-12-31", status: "active" },
    ],
    qualifiers: [{ name: "David Kim", trades: ["hvac"], states: ["SC", "NC"] }],
    insurance: { generalLiability: { amount: 1000000, expiry: "2026-09-15" }, workersComp: true },
    bonds: [],
    registrations: [],
    createdAt: "2023-04-03",
  },
  {
    id: "co-3",
    legalName: "Tri-State Fire & Mechanical LLC",
    entityType: "llc",
    incorporatedStates: ["VA"],
    foreignQualifications: ["NC"],
    licenses: [
      { id: "l6", state: "VA", trade: "fire-protection", classification: "Class A", licenseNumber: "VA-2705-112341", qualifier: "Aisha Johnson", issuedDate: "2022-08-11", expiryDate: "2027-02-28", status: "active" },
      { id: "l7", state: "NC", trade: "fire-protection", classification: "Unlimited", licenseNumber: "NC-FS-15502", qualifier: "Aisha Johnson", issuedDate: "2023-02-20", expiryDate: "2026-08-20", status: "active" },
    ],
    qualifiers: [{ name: "Aisha Johnson", trades: ["fire-protection"], states: ["VA", "NC"] }],
    insurance: { generalLiability: { amount: 2000000, expiry: "2027-01-01" }, workersComp: true },
    bonds: [{ state: "VA", amount: 15000 }],
    registrations: [],
    createdAt: "2022-11-11",
  },
];

export const MOCK_PROJECTS: ProjectInput[] = [
  {
    id: "pj-1",
    title: "Atrium Health — HVAC Retrofit Phase 2",
    address: "1000 Blythe Blvd",
    city: "Charlotte",
    county: "Mecklenburg",
    state: "NC",
    trade: "hvac",
    scope: "Hospital HVAC retrofit + controls — 120 ton chiller replacement, BMS upgrade",
    contractValue: 1400000,
    role: "subcontractor",
    isPublicWorks: false,
    bidDate: "2026-09-15",
    estimatedStartDate: "2026-10-20",
  },
  {
    id: "pj-2",
    title: "City of Raleigh — Fire Station 23 Electrical",
    address: "18 W Martin St",
    city: "Raleigh",
    county: "Wake",
    state: "NC",
    trade: "electrical",
    scope: "New fire station 23: service, distribution, fire alarm, emergency generator",
    contractValue: 820000,
    role: "subcontractor",
    isPublicWorks: true,
    bidDate: "2026-09-02",
    estimatedStartDate: "2026-10-01",
  },
  {
    id: "pj-3",
    title: "Charleston Tech Campus — Core & Shell Electrical",
    address: "145 King St",
    city: "Charleston",
    county: "Charleston",
    state: "SC",
    trade: "electrical",
    scope: "175k SF tech campus core electrical + EV charging mezzanine",
    contractValue: 2400000,
    role: "general-contractor",
    isPublicWorks: false,
    bidDate: "2026-08-28",
    estimatedStartDate: "2026-09-22",
  },
  {
    id: "pj-4",
    title: "Richmond VCU Med — Fire Sprinkler Retrofit",
    address: "1250 E Marshall St",
    city: "Richmond",
    county: "Richmond City",
    state: "VA",
    trade: "fire-protection",
    scope: "Medical tower fire sprinkler retrofit, 9 floors",
    contractValue: 450000,
    role: "subcontractor",
    isPublicWorks: false,
    bidDate: "2026-09-10",
    estimatedStartDate: "2026-10-15",
  },
];

export const TRADE_LABEL: Record<string, string> = {
  electrical: "Electrical",
  hvac: "HVAC / Mechanical",
  "fire-protection": "Fire Protection",
  plumbing: "Plumbing",
  general: "General",
};
